splits:
  train: 0.8
  val: 0.2
  test: 0.0

split_cols_in_dataset:
  train: 'train'
  val: 'val'
  test: 'test'

tokenize_data:
  args:
    pretrain_or_finetune:
      train_val:
        max_length: 2048
        use_cls: False
        label_at_each_utt: False
        append_label: False
        prepend_label: False
        lm_prompt_break_at_utt: False
        lm_label_break_at_utt: False
        lm_also_include_convo: False
      val_test:
        max_length: 2048
        use_cls: False
        label_at_each_utt: True
        append_label: False
        prepend_label: False
        lm_prompt_break_at_utt: False
        lm_label_break_at_utt: False
        lm_also_include_convo: False
    finetune_as_lm:
      train_val:
        max_length: 2048
        use_cls: False
        label_at_each_utt: False
        append_label: True
        prepend_label: True
        lm_prompt_break_at_utt: True
        lm_label_break_at_utt: False
        lm_also_include_convo: False
      val_test:
        max_length: null
        use_cls: False
        label_at_each_utt: False
        append_label: True
        prepend_label: False
        lm_prompt_break_at_utt: False
        lm_label_break_at_utt: False
        lm_also_include_convo: False
