nn_model:
  id: 'convo_wizard'
  transformer:
    args:
      embedding_dim: 300
      hidden_dim: 512
      max_relative_position: None
      use_sinusoidal_init: True
      positional_network_type: 'ffnn'
      output_dim: 2
      classifier_head_type: 'rnn'
      num_heads: 6
      num_encoder_layers: 4
      max_length: 2048
      pad_token_position: 0
      pad_tok_type: 0
      num_token_types: 2
      attention_dropout: 0.05
      dropout: 0.1
  optimizer:
    args:
      lr: 2.0e-3
      betas: [ 0.9, 0.999 ]
      eps: 1.0e-9
      num_warmup_steps: 4000
  trainer:
    args:
      is_labeled_data:
        - id: 'generator'
          labeled_data: False
        - id: 'discriminator'
          labeled_data: True
      labels_ignore_idx:
        - id: 'generator'
          ignore_idx: 0
        - id: 'discriminator'
          ignore_idx: -100
      use_class_weights: False
      batch_size: 1
      gradient_clip_value: 0.75

train_eval:
  args:
    batch_size: 32
    num_epochs: 8
